### ISSUE TITLE
pymongo.errors.ServerSelectionTimeoutError

### ISSUE THREAD

**Issue by daisy613** [CryptoGnome/LickHunterPRO#7]
2020-09-02T09:56:49: Traceback (most recent call last):
2020-09-02T09:56:49:   File "binanceWebsocket.py", line 291, in <module>
2020-09-02T09:56:49:   File "site-packages\pymongo\collection.py", line 1273, in find_one
2020-09-02T09:56:49:   File "site-packages\pymongo\cursor.py", line 1156, in next
2020-09-02T09:56:49:   File "site-packages\pymongo\cursor.py", line 1050, in _refresh
2020-09-02T09:56:49:   File "site-packages\pymongo\mongo_client.py", line 1810, in _ensure_session
2020-09-02T09:56:49:   File "site-packages\pymongo\mongo_client.py", line 1763, in __start_session
2020-09-02T09:56:49:   File "site-packages\pymongo\mongo_client.py", line 1796, in _get_server_session
2020-09-02T09:56:49:   File "site-packages\pymongo\topology.py", line 487, in get_server_session
2020-09-02T09:56:49:   File "site-packages\pymongo\topology.py", line 208, in _select_servers_loop
2020-09-02T09:56:49: pymongo.errors.ServerSelectionTimeoutError: SSL handshake failed: cluster0-shard-00-02-rsyek.gcp.mongodb.net:27017: _ssl.c:1091: The handshake operation timed out,SSL handshake failed: cluster0-shard-00-00-rsyek.gcp.mongodb.net:27017: _ssl.c:1091: The handshake operation timed out,SSL handshake failed: cluster0-shard-00-01-rsyek.gcp.mongodb.net:27017: _ssl.c:1091: The handshake operation timed out
2020-09-02T09:56:49: cript binanceWebsocket

**Comment by CryptoGnome** [comment]
this should resolve itself with use of PM2 and can be ignored... How many restarts are you seeing in the Monitor?
